//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProyecto3.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public string rut_cliente { get; set; }
        public string nombre_cliente { get; set; }
        public string apellido_cliente { get; set; }
        public int edad_cliente { get; set; }
        public string sexo_cliente { get; set; }
        public Nullable<int> id_boleta { get; set; }
        public Nullable<int> id_factura { get; set; }
    
        public virtual BOLETA BOLETA { get; set; }
        public virtual FACTURA FACTURA { get; set; }
    }
}
