//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProyecto3.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public int id_factura { get; set; }
        public int monto_factura { get; set; }
        public int monto_iva_factura { get; set; }
        public Nullable<System.DateTime> fecha_ingreso_factura { get; set; }
        public Nullable<System.DateTime> fecha_entrega_factura { get; set; }
        public string descripcion_factura { get; set; }
        public string descripcion_cliente_factura { get; set; }
        public string rut_factura { get; set; }
        public string rut_cliente_factura { get; set; }
        public string rut_empresa_factura { get; set; }
        public string patente_producto_factura { get; set; }
        public string tipo_servicio_factura { get; set; }
        public Nullable<int> id_venta { get; set; }
        public string rut_empresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual VENTA VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
