//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProyecto3.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public int id_servicio { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public int costo_servicio { get; set; }
        public string patente_servicio { get; set; }
        public string descripcion { get; set; }
    }
}
