//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaProyecto3.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENDEDOR()
        {
            this.VENTA = new HashSet<VENTA>();
        }
    
        public string rut_vendedor { get; set; }
        public string nombre_vendedor { get; set; }
        public string apellidos_vendedor { get; set; }
        public int edad_vendedor { get; set; }
        public string sexo_vendedor { get; set; }
        public int sueldo_vendedor { get; set; }
        public int bono_vendedor { get; set; }
        public int ventas_totales { get; set; }
        public Nullable<int> id_sucursal { get; set; }
    
        public virtual SUCURSAL SUCURSAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA> VENTA { get; set; }
    }
}
